-- MySQL Script generated by MySQL Workbench
-- Fri Oct 25 00:34:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bugs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bugs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bugs` DEFAULT CHARACTER SET utf8 ;
USE `bugs` ;

-- -----------------------------------------------------
-- Table `bugs`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`profiles` (
  `userid` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(255) NOT NULL,
  `cryptpassword` VARCHAR(128) NULL DEFAULT NULL,
  `realname` VARCHAR(255) NOT NULL DEFAULT '',
  `disabledtext` MEDIUMTEXT NOT NULL,
  `disable_mail` TINYINT(4) NOT NULL DEFAULT '0',
  `mybugslink` TINYINT(4) NOT NULL DEFAULT '1',
  `extern_id` VARCHAR(64) NULL DEFAULT NULL,
  `is_enabled` TINYINT(4) NOT NULL DEFAULT '1',
  `last_seen_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `profiles_login_name_idx` (`login_name` ASC),
  UNIQUE INDEX `profiles_extern_id_idx` (`extern_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`classifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`classifications` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `classifications_name_idx` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`products` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `classification_id` SMALLINT(6) NOT NULL DEFAULT '1',
  `description` MEDIUMTEXT NOT NULL,
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `defaultmilestone` VARCHAR(64) NOT NULL DEFAULT '---',
  `allows_unconfirmed` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `products_name_idx` (`name` ASC),
  INDEX `fk_products_classification_id_classifications_id` (`classification_id` ASC),
  CONSTRAINT `fk_products_classification_id_classifications_id`
    FOREIGN KEY (`classification_id`)
    REFERENCES `bugs`.`classifications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`components` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `product_id` SMALLINT(6) NOT NULL,
  `initialowner` MEDIUMINT(9) NOT NULL,
  `initialqacontact` MEDIUMINT(9) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `components_product_id_idx` (`product_id` ASC, `name` ASC),
  INDEX `components_name_idx` (`name` ASC),
  INDEX `fk_components_initialqacontact_profiles_userid` (`initialqacontact` ASC),
  INDEX `fk_components_initialowner_profiles_userid` (`initialowner` ASC),
  CONSTRAINT `fk_components_initialowner_profiles_userid`
    FOREIGN KEY (`initialowner`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_components_initialqacontact_profiles_userid`
    FOREIGN KEY (`initialqacontact`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_components_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bugs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bugs` (
  `bug_id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `assigned_to` MEDIUMINT(9) NOT NULL,
  `bug_file_loc` MEDIUMTEXT NOT NULL,
  `bug_severity` VARCHAR(64) NOT NULL,
  `bug_status` VARCHAR(64) NOT NULL,
  `creation_ts` DATETIME NULL DEFAULT NULL,
  `delta_ts` DATETIME NOT NULL,
  `short_desc` VARCHAR(255) NOT NULL,
  `op_sys` VARCHAR(64) NOT NULL,
  `priority` VARCHAR(64) NOT NULL,
  `product_id` SMALLINT(6) NOT NULL,
  `rep_platform` VARCHAR(64) NOT NULL,
  `reporter` MEDIUMINT(9) NOT NULL,
  `version` VARCHAR(64) NOT NULL,
  `component_id` MEDIUMINT(9) NOT NULL,
  `resolution` VARCHAR(64) NOT NULL DEFAULT '',
  `target_milestone` VARCHAR(64) NOT NULL DEFAULT '---',
  `qa_contact` MEDIUMINT(9) NULL DEFAULT NULL,
  `status_whiteboard` MEDIUMTEXT NOT NULL,
  `lastdiffed` DATETIME NULL DEFAULT NULL,
  `everconfirmed` TINYINT(4) NOT NULL,
  `reporter_accessible` TINYINT(4) NOT NULL DEFAULT '1',
  `cclist_accessible` TINYINT(4) NOT NULL DEFAULT '1',
  `estimated_time` DECIMAL(7,2) NOT NULL DEFAULT '0.00',
  `remaining_time` DECIMAL(7,2) NOT NULL DEFAULT '0.00',
  `deadline` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`bug_id`),
  INDEX `bugs_assigned_to_idx` (`assigned_to` ASC),
  INDEX `bugs_creation_ts_idx` (`creation_ts` ASC),
  INDEX `bugs_delta_ts_idx` (`delta_ts` ASC),
  INDEX `bugs_bug_severity_idx` (`bug_severity` ASC),
  INDEX `bugs_bug_status_idx` (`bug_status` ASC),
  INDEX `bugs_op_sys_idx` (`op_sys` ASC),
  INDEX `bugs_priority_idx` (`priority` ASC),
  INDEX `bugs_product_id_idx` (`product_id` ASC),
  INDEX `bugs_reporter_idx` (`reporter` ASC),
  INDEX `bugs_version_idx` (`version` ASC),
  INDEX `bugs_component_id_idx` (`component_id` ASC),
  INDEX `bugs_resolution_idx` (`resolution` ASC),
  INDEX `bugs_target_milestone_idx` (`target_milestone` ASC),
  INDEX `bugs_qa_contact_idx` (`qa_contact` ASC),
  CONSTRAINT `fk_bugs_assigned_to_profiles_userid`
    FOREIGN KEY (`assigned_to`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_component_id_components_id`
    FOREIGN KEY (`component_id`)
    REFERENCES `bugs`.`components` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_qa_contact_profiles_userid`
    FOREIGN KEY (`qa_contact`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_reporter_profiles_userid`
    FOREIGN KEY (`reporter`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`attachments` (
  `attach_id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `creation_ts` DATETIME NOT NULL,
  `modification_time` DATETIME NOT NULL,
  `description` TINYTEXT NOT NULL,
  `mimetype` TINYTEXT NOT NULL,
  `ispatch` TINYINT(4) NOT NULL DEFAULT '0',
  `filename` VARCHAR(255) NOT NULL,
  `submitter_id` MEDIUMINT(9) NOT NULL,
  `isobsolete` TINYINT(4) NOT NULL DEFAULT '0',
  `isprivate` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`attach_id`),
  INDEX `attachments_bug_id_idx` (`bug_id` ASC),
  INDEX `attachments_creation_ts_idx` (`creation_ts` ASC),
  INDEX `attachments_modification_time_idx` (`modification_time` ASC),
  INDEX `attachments_submitter_id_idx` (`submitter_id` ASC, `bug_id` ASC),
  CONSTRAINT `fk_attachments_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attachments_submitter_id_profiles_userid`
    FOREIGN KEY (`submitter_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`attach_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`attach_data` (
  `id` MEDIUMINT(9) NOT NULL,
  `thedata` LONGBLOB NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_attach_data_id_attachments_attach_id`
    FOREIGN KEY (`id`)
    REFERENCES `bugs`.`attachments` (`attach_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AVG_ROW_LENGTH = 1000000
DEFAULT CHARACTER SET = utf8
MAX_ROWS = 100000;


-- -----------------------------------------------------
-- Table `bugs`.`audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`audit_log` (
  `user_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `class` VARCHAR(255) NOT NULL,
  `object_id` INT(11) NOT NULL,
  `field` VARCHAR(64) NOT NULL,
  `removed` MEDIUMTEXT NULL DEFAULT NULL,
  `added` MEDIUMTEXT NULL DEFAULT NULL,
  `at_time` DATETIME NOT NULL,
  INDEX `audit_log_class_idx` (`class` ASC, `at_time` ASC),
  INDEX `fk_audit_log_user_id_profiles_userid` (`user_id` ASC),
  CONSTRAINT `fk_audit_log_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`groups` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `isbuggroup` TINYINT(4) NOT NULL,
  `userregexp` TINYTEXT NOT NULL,
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `icon_url` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `groups_name_idx` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bug_group_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bug_group_map` (
  `bug_id` MEDIUMINT(9) NOT NULL,
  `group_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `bug_group_map_bug_id_idx` (`bug_id` ASC, `group_id` ASC),
  INDEX `bug_group_map_group_id_idx` (`group_id` ASC),
  CONSTRAINT `fk_bug_group_map_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bug_group_map_group_id_groups_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bug_see_also`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bug_see_also` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `class` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bug_see_also_bug_id_idx` (`bug_id` ASC, `value` ASC),
  CONSTRAINT `fk_bug_see_also_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bug_severity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bug_severity` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `visibility_value_id` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bug_severity_value_idx` (`value` ASC),
  INDEX `bug_severity_sortkey_idx` (`sortkey` ASC, `value` ASC),
  INDEX `bug_severity_visibility_value_id_idx` (`visibility_value_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bug_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bug_status` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `visibility_value_id` SMALLINT(6) NULL DEFAULT NULL,
  `is_open` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bug_status_value_idx` (`value` ASC),
  INDEX `bug_status_sortkey_idx` (`sortkey` ASC, `value` ASC),
  INDEX `bug_status_visibility_value_id_idx` (`visibility_value_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`tag` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `user_id` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tag_user_id_idx` (`user_id` ASC, `name` ASC),
  CONSTRAINT `fk_tag_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bug_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bug_tag` (
  `bug_id` MEDIUMINT(9) NOT NULL,
  `tag_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `bug_tag_bug_id_idx` (`bug_id` ASC, `tag_id` ASC),
  INDEX `fk_bug_tag_tag_id_tag_id` (`tag_id` ASC),
  CONSTRAINT `fk_bug_tag_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bug_tag_tag_id_tag_id`
    FOREIGN KEY (`tag_id`)
    REFERENCES `bugs`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bug_user_last_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bug_user_last_visit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` MEDIUMINT(9) NOT NULL,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `last_visit_ts` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bug_user_last_visit_idx` (`user_id` ASC, `bug_id` ASC),
  INDEX `bug_user_last_visit_last_visit_ts_idx` (`last_visit_ts` ASC),
  INDEX `fk_bug_user_last_visit_bug_id_bugs_bug_id` (`bug_id` ASC),
  CONSTRAINT `fk_bug_user_last_visit_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bug_user_last_visit_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`longdescs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`longdescs` (
  `comment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `who` MEDIUMINT(9) NOT NULL,
  `bug_when` DATETIME NOT NULL,
  `work_time` DECIMAL(7,2) NOT NULL DEFAULT '0.00',
  `thetext` MEDIUMTEXT NOT NULL,
  `isprivate` TINYINT(4) NOT NULL DEFAULT '0',
  `already_wrapped` TINYINT(4) NOT NULL DEFAULT '0',
  `type` SMALLINT(6) NOT NULL DEFAULT '0',
  `extra_data` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `longdescs_bug_id_idx` (`bug_id` ASC, `work_time` ASC),
  INDEX `longdescs_who_idx` (`who` ASC, `bug_id` ASC),
  INDEX `longdescs_bug_when_idx` (`bug_when` ASC),
  CONSTRAINT `fk_longdescs_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_longdescs_who_profiles_userid`
    FOREIGN KEY (`who`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`fielddefs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`fielddefs` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `type` SMALLINT(6) NOT NULL DEFAULT '0',
  `custom` TINYINT(4) NOT NULL DEFAULT '0',
  `description` TINYTEXT NOT NULL,
  `long_desc` VARCHAR(255) NOT NULL DEFAULT '',
  `mailhead` TINYINT(4) NOT NULL DEFAULT '0',
  `sortkey` SMALLINT(6) NOT NULL,
  `obsolete` TINYINT(4) NOT NULL DEFAULT '0',
  `enter_bug` TINYINT(4) NOT NULL DEFAULT '0',
  `buglist` TINYINT(4) NOT NULL DEFAULT '0',
  `visibility_field_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `value_field_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `reverse_desc` TINYTEXT NULL DEFAULT NULL,
  `is_mandatory` TINYINT(4) NOT NULL DEFAULT '0',
  `is_numeric` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fielddefs_name_idx` (`name` ASC),
  INDEX `fielddefs_sortkey_idx` (`sortkey` ASC),
  INDEX `fielddefs_value_field_id_idx` (`value_field_id` ASC),
  INDEX `fielddefs_is_mandatory_idx` (`is_mandatory` ASC),
  INDEX `fk_fielddefs_visibility_field_id_fielddefs_id` (`visibility_field_id` ASC),
  CONSTRAINT `fk_fielddefs_value_field_id_fielddefs_id`
    FOREIGN KEY (`value_field_id`)
    REFERENCES `bugs`.`fielddefs` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fielddefs_visibility_field_id_fielddefs_id`
    FOREIGN KEY (`visibility_field_id`)
    REFERENCES `bugs`.`fielddefs` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bugs_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bugs_activity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `attach_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `who` MEDIUMINT(9) NOT NULL,
  `bug_when` DATETIME NOT NULL,
  `fieldid` MEDIUMINT(9) NOT NULL,
  `added` VARCHAR(255) NULL DEFAULT NULL,
  `removed` VARCHAR(255) NULL DEFAULT NULL,
  `comment_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `bugs_activity_bug_id_idx` (`bug_id` ASC),
  INDEX `bugs_activity_who_idx` (`who` ASC),
  INDEX `bugs_activity_bug_when_idx` (`bug_when` ASC),
  INDEX `bugs_activity_fieldid_idx` (`fieldid` ASC),
  INDEX `bugs_activity_added_idx` (`added` ASC),
  INDEX `bugs_activity_removed_idx` (`removed` ASC),
  INDEX `fk_bugs_activity_attach_id_attachments_attach_id` (`attach_id` ASC),
  INDEX `fk_bugs_activity_comment_id_longdescs_comment_id` (`comment_id` ASC),
  CONSTRAINT `fk_bugs_activity_attach_id_attachments_attach_id`
    FOREIGN KEY (`attach_id`)
    REFERENCES `bugs`.`attachments` (`attach_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_activity_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_activity_comment_id_longdescs_comment_id`
    FOREIGN KEY (`comment_id`)
    REFERENCES `bugs`.`longdescs` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_activity_fieldid_fielddefs_id`
    FOREIGN KEY (`fieldid`)
    REFERENCES `bugs`.`fielddefs` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bugs_activity_who_profiles_userid`
    FOREIGN KEY (`who`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bugs_aliases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bugs_aliases` (
  `alias` VARCHAR(40) NOT NULL,
  `bug_id` MEDIUMINT(9) NULL DEFAULT NULL,
  UNIQUE INDEX `bugs_aliases_alias_idx` (`alias` ASC),
  INDEX `bugs_aliases_bug_id_idx` (`bug_id` ASC),
  CONSTRAINT `fk_bugs_aliases_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bugs_fulltext`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bugs_fulltext` (
  `bug_id` MEDIUMINT(9) NOT NULL,
  `short_desc` VARCHAR(255) NOT NULL,
  `comments` MEDIUMTEXT NULL DEFAULT NULL,
  `comments_noprivate` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`bug_id`),
  FULLTEXT INDEX `bugs_fulltext_short_desc_idx` (`short_desc` ASC),
  FULLTEXT INDEX `bugs_fulltext_comments_idx` (`comments` ASC),
  FULLTEXT INDEX `bugs_fulltext_comments_noprivate_idx` (`comments_noprivate` ASC),
  CONSTRAINT `fk_bugs_fulltext_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`bz_schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`bz_schema` (
  `schema_data` LONGBLOB NOT NULL,
  `version` DECIMAL(3,2) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`series_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`series_categories` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `series_categories_name_idx` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`category_group_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`category_group_map` (
  `category_id` SMALLINT(6) NOT NULL,
  `group_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `category_group_map_category_id_idx` (`category_id` ASC, `group_id` ASC),
  INDEX `fk_category_group_map_group_id_groups_id` (`group_id` ASC),
  CONSTRAINT `fk_category_group_map_category_id_series_categories_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `bugs`.`series_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_category_group_map_group_id_groups_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`cc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`cc` (
  `bug_id` MEDIUMINT(9) NOT NULL,
  `who` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `cc_bug_id_idx` (`bug_id` ASC, `who` ASC),
  INDEX `cc_who_idx` (`who` ASC),
  CONSTRAINT `fk_cc_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cc_who_profiles_userid`
    FOREIGN KEY (`who`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`component_cc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`component_cc` (
  `user_id` MEDIUMINT(9) NOT NULL,
  `component_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `component_cc_user_id_idx` (`component_id` ASC, `user_id` ASC),
  INDEX `fk_component_cc_user_id_profiles_userid` (`user_id` ASC),
  CONSTRAINT `fk_component_cc_component_id_components_id`
    FOREIGN KEY (`component_id`)
    REFERENCES `bugs`.`components` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_component_cc_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`dependencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`dependencies` (
  `blocked` MEDIUMINT(9) NOT NULL,
  `dependson` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `dependencies_blocked_idx` (`blocked` ASC, `dependson` ASC),
  INDEX `dependencies_dependson_idx` (`dependson` ASC),
  CONSTRAINT `fk_dependencies_blocked_bugs_bug_id`
    FOREIGN KEY (`blocked`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dependencies_dependson_bugs_bug_id`
    FOREIGN KEY (`dependson`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`duplicates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`duplicates` (
  `dupe_of` MEDIUMINT(9) NOT NULL,
  `dupe` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`dupe`),
  INDEX `fk_duplicates_dupe_of_bugs_bug_id` (`dupe_of` ASC),
  CONSTRAINT `fk_duplicates_dupe_bugs_bug_id`
    FOREIGN KEY (`dupe`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_duplicates_dupe_of_bugs_bug_id`
    FOREIGN KEY (`dupe_of`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`email_bug_ignore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`email_bug_ignore` (
  `user_id` MEDIUMINT(9) NOT NULL,
  `bug_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `email_bug_ignore_user_id_idx` (`user_id` ASC, `bug_id` ASC),
  INDEX `fk_email_bug_ignore_bug_id_bugs_bug_id` (`bug_id` ASC),
  CONSTRAINT `fk_email_bug_ignore_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_email_bug_ignore_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`email_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`email_setting` (
  `user_id` MEDIUMINT(9) NOT NULL,
  `relationship` TINYINT(4) NOT NULL,
  `event` TINYINT(4) NOT NULL,
  UNIQUE INDEX `email_setting_user_id_idx` (`user_id` ASC, `relationship` ASC, `event` ASC),
  CONSTRAINT `fk_email_setting_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`field_visibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`field_visibility` (
  `field_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `value_id` SMALLINT(6) NOT NULL,
  UNIQUE INDEX `field_visibility_field_id_idx` (`field_id` ASC, `value_id` ASC),
  CONSTRAINT `fk_field_visibility_field_id_fielddefs_id`
    FOREIGN KEY (`field_id`)
    REFERENCES `bugs`.`fielddefs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`flagtypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`flagtypes` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `cc_list` VARCHAR(200) NULL DEFAULT NULL,
  `target_type` CHAR(1) NOT NULL DEFAULT 'b',
  `is_active` TINYINT(4) NOT NULL DEFAULT '1',
  `is_requestable` TINYINT(4) NOT NULL DEFAULT '0',
  `is_requesteeble` TINYINT(4) NOT NULL DEFAULT '0',
  `is_multiplicable` TINYINT(4) NOT NULL DEFAULT '0',
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `grant_group_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `request_group_id` MEDIUMINT(9) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flagtypes_grant_group_id_groups_id` (`grant_group_id` ASC),
  INDEX `fk_flagtypes_request_group_id_groups_id` (`request_group_id` ASC),
  CONSTRAINT `fk_flagtypes_grant_group_id_groups_id`
    FOREIGN KEY (`grant_group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flagtypes_request_group_id_groups_id`
    FOREIGN KEY (`request_group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`flagexclusions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`flagexclusions` (
  `type_id` MEDIUMINT(9) NOT NULL,
  `product_id` SMALLINT(6) NULL DEFAULT NULL,
  `component_id` MEDIUMINT(9) NULL DEFAULT NULL,
  UNIQUE INDEX `flagexclusions_type_id_idx` (`type_id` ASC, `product_id` ASC, `component_id` ASC),
  INDEX `fk_flagexclusions_product_id_products_id` (`product_id` ASC),
  INDEX `fk_flagexclusions_component_id_components_id` (`component_id` ASC),
  CONSTRAINT `fk_flagexclusions_component_id_components_id`
    FOREIGN KEY (`component_id`)
    REFERENCES `bugs`.`components` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flagexclusions_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flagexclusions_type_id_flagtypes_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `bugs`.`flagtypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`flaginclusions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`flaginclusions` (
  `type_id` MEDIUMINT(9) NOT NULL,
  `product_id` SMALLINT(6) NULL DEFAULT NULL,
  `component_id` MEDIUMINT(9) NULL DEFAULT NULL,
  UNIQUE INDEX `flaginclusions_type_id_idx` (`type_id` ASC, `product_id` ASC, `component_id` ASC),
  INDEX `fk_flaginclusions_product_id_products_id` (`product_id` ASC),
  INDEX `fk_flaginclusions_component_id_components_id` (`component_id` ASC),
  CONSTRAINT `fk_flaginclusions_component_id_components_id`
    FOREIGN KEY (`component_id`)
    REFERENCES `bugs`.`components` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flaginclusions_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flaginclusions_type_id_flagtypes_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `bugs`.`flagtypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`flags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`flags` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `type_id` MEDIUMINT(9) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `attach_id` MEDIUMINT(9) NULL DEFAULT NULL,
  `creation_date` DATETIME NOT NULL,
  `modification_date` DATETIME NULL DEFAULT NULL,
  `setter_id` MEDIUMINT(9) NOT NULL,
  `requestee_id` MEDIUMINT(9) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `flags_bug_id_idx` (`bug_id` ASC, `attach_id` ASC),
  INDEX `flags_setter_id_idx` (`setter_id` ASC),
  INDEX `flags_requestee_id_idx` (`requestee_id` ASC),
  INDEX `flags_type_id_idx` (`type_id` ASC),
  INDEX `fk_flags_attach_id_attachments_attach_id` (`attach_id` ASC),
  CONSTRAINT `fk_flags_attach_id_attachments_attach_id`
    FOREIGN KEY (`attach_id`)
    REFERENCES `bugs`.`attachments` (`attach_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flags_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flags_requestee_id_profiles_userid`
    FOREIGN KEY (`requestee_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flags_setter_id_profiles_userid`
    FOREIGN KEY (`setter_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flags_type_id_flagtypes_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `bugs`.`flagtypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`group_control_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`group_control_map` (
  `group_id` MEDIUMINT(9) NOT NULL,
  `product_id` SMALLINT(6) NOT NULL,
  `entry` TINYINT(4) NOT NULL DEFAULT '0',
  `membercontrol` TINYINT(4) NOT NULL DEFAULT '0',
  `othercontrol` TINYINT(4) NOT NULL DEFAULT '0',
  `canedit` TINYINT(4) NOT NULL DEFAULT '0',
  `editcomponents` TINYINT(4) NOT NULL DEFAULT '0',
  `editbugs` TINYINT(4) NOT NULL DEFAULT '0',
  `canconfirm` TINYINT(4) NOT NULL DEFAULT '0',
  UNIQUE INDEX `group_control_map_product_id_idx` (`product_id` ASC, `group_id` ASC),
  INDEX `group_control_map_group_id_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_control_map_group_id_groups_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group_control_map_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`group_group_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`group_group_map` (
  `member_id` MEDIUMINT(9) NOT NULL,
  `grantor_id` MEDIUMINT(9) NOT NULL,
  `grant_type` TINYINT(4) NOT NULL DEFAULT '0',
  UNIQUE INDEX `group_group_map_member_id_idx` (`member_id` ASC, `grantor_id` ASC, `grant_type` ASC),
  INDEX `fk_group_group_map_grantor_id_groups_id` (`grantor_id` ASC),
  CONSTRAINT `fk_group_group_map_grantor_id_groups_id`
    FOREIGN KEY (`grantor_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group_group_map_member_id_groups_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`keyworddefs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`keyworddefs` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `keyworddefs_name_idx` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`keywords` (
  `bug_id` MEDIUMINT(9) NOT NULL,
  `keywordid` SMALLINT(6) NOT NULL,
  UNIQUE INDEX `keywords_bug_id_idx` (`bug_id` ASC, `keywordid` ASC),
  INDEX `keywords_keywordid_idx` (`keywordid` ASC),
  CONSTRAINT `fk_keywords_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_keywords_keywordid_keyworddefs_id`
    FOREIGN KEY (`keywordid`)
    REFERENCES `bugs`.`keyworddefs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`login_failure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`login_failure` (
  `user_id` MEDIUMINT(9) NOT NULL,
  `login_time` DATETIME NOT NULL,
  `ip_addr` VARCHAR(40) NOT NULL,
  INDEX `login_failure_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_login_failure_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`logincookies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`logincookies` (
  `cookie` VARCHAR(16) NOT NULL,
  `userid` MEDIUMINT(9) NOT NULL,
  `ipaddr` VARCHAR(40) NULL DEFAULT NULL,
  `lastused` DATETIME NOT NULL,
  PRIMARY KEY (`cookie`),
  INDEX `logincookies_lastused_idx` (`lastused` ASC),
  INDEX `fk_logincookies_userid_profiles_userid` (`userid` ASC),
  CONSTRAINT `fk_logincookies_userid_profiles_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`longdescs_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`longdescs_tags` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `comment_id` INT(11) NULL DEFAULT NULL,
  `tag` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `longdescs_tags_idx` (`comment_id` ASC, `tag` ASC),
  CONSTRAINT `fk_longdescs_tags_comment_id_longdescs_comment_id`
    FOREIGN KEY (`comment_id`)
    REFERENCES `bugs`.`longdescs` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`longdescs_tags_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`longdescs_tags_activity` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `bug_id` MEDIUMINT(9) NOT NULL,
  `comment_id` INT(11) NULL DEFAULT NULL,
  `who` MEDIUMINT(9) NOT NULL,
  `bug_when` DATETIME NOT NULL,
  `added` VARCHAR(24) NULL DEFAULT NULL,
  `removed` VARCHAR(24) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `longdescs_tags_activity_bug_id_idx` (`bug_id` ASC),
  INDEX `fk_longdescs_tags_activity_who_profiles_userid` (`who` ASC),
  INDEX `fk_longdescs_tags_activity_comment_id_longdescs_comment_id` (`comment_id` ASC),
  CONSTRAINT `fk_longdescs_tags_activity_bug_id_bugs_bug_id`
    FOREIGN KEY (`bug_id`)
    REFERENCES `bugs`.`bugs` (`bug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_longdescs_tags_activity_comment_id_longdescs_comment_id`
    FOREIGN KEY (`comment_id`)
    REFERENCES `bugs`.`longdescs` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_longdescs_tags_activity_who_profiles_userid`
    FOREIGN KEY (`who`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`longdescs_tags_weights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`longdescs_tags_weights` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(24) NOT NULL,
  `weight` MEDIUMINT(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `longdescs_tags_weights_tag_idx` (`tag` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`mail_staging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`mail_staging` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `message` LONGBLOB NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`milestones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`milestones` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `product_id` SMALLINT(6) NOT NULL,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `milestones_product_id_idx` (`product_id` ASC, `value` ASC),
  CONSTRAINT `fk_milestones_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`namedqueries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`namedqueries` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `userid` MEDIUMINT(9) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `query` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `namedqueries_userid_idx` (`userid` ASC, `name` ASC),
  CONSTRAINT `fk_namedqueries_userid_profiles_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`namedqueries_link_in_footer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`namedqueries_link_in_footer` (
  `namedquery_id` MEDIUMINT(9) NOT NULL,
  `user_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `namedqueries_link_in_footer_id_idx` (`namedquery_id` ASC, `user_id` ASC),
  INDEX `namedqueries_link_in_footer_userid_idx` (`user_id` ASC),
  CONSTRAINT `fk_namedqueries_link_in_footer_namedquery_id_namedqueries_id`
    FOREIGN KEY (`namedquery_id`)
    REFERENCES `bugs`.`namedqueries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_namedqueries_link_in_footer_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`namedquery_group_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`namedquery_group_map` (
  `namedquery_id` MEDIUMINT(9) NOT NULL,
  `group_id` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `namedquery_group_map_namedquery_id_idx` (`namedquery_id` ASC),
  INDEX `namedquery_group_map_group_id_idx` (`group_id` ASC),
  CONSTRAINT `fk_namedquery_group_map_group_id_groups_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_namedquery_group_map_namedquery_id_namedqueries_id`
    FOREIGN KEY (`namedquery_id`)
    REFERENCES `bugs`.`namedqueries` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`op_sys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`op_sys` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `visibility_value_id` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `op_sys_value_idx` (`value` ASC),
  INDEX `op_sys_sortkey_idx` (`sortkey` ASC, `value` ASC),
  INDEX `op_sys_visibility_value_id_idx` (`visibility_value_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`priority` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `visibility_value_id` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `priority_value_idx` (`value` ASC),
  INDEX `priority_sortkey_idx` (`sortkey` ASC, `value` ASC),
  INDEX `priority_visibility_value_id_idx` (`visibility_value_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`profile_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`profile_search` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` MEDIUMINT(9) NOT NULL,
  `bug_list` MEDIUMTEXT NOT NULL,
  `list_order` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `profile_search_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_profile_search_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`setting` (
  `name` VARCHAR(32) NOT NULL,
  `default_value` VARCHAR(32) NOT NULL,
  `is_enabled` TINYINT(4) NOT NULL DEFAULT '1',
  `subclass` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`profile_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`profile_setting` (
  `user_id` MEDIUMINT(9) NOT NULL,
  `setting_name` VARCHAR(32) NOT NULL,
  `setting_value` VARCHAR(32) NOT NULL,
  UNIQUE INDEX `profile_setting_value_unique_idx` (`user_id` ASC, `setting_name` ASC),
  INDEX `fk_profile_setting_setting_name_setting_name` (`setting_name` ASC),
  CONSTRAINT `fk_profile_setting_setting_name_setting_name`
    FOREIGN KEY (`setting_name`)
    REFERENCES `bugs`.`setting` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_profile_setting_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`profiles_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`profiles_activity` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `userid` MEDIUMINT(9) NOT NULL,
  `who` MEDIUMINT(9) NOT NULL,
  `profiles_when` DATETIME NOT NULL,
  `fieldid` MEDIUMINT(9) NOT NULL,
  `oldvalue` TINYTEXT NULL DEFAULT NULL,
  `newvalue` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `profiles_activity_userid_idx` (`userid` ASC),
  INDEX `profiles_activity_profiles_when_idx` (`profiles_when` ASC),
  INDEX `profiles_activity_fieldid_idx` (`fieldid` ASC),
  INDEX `fk_profiles_activity_who_profiles_userid` (`who` ASC),
  CONSTRAINT `fk_profiles_activity_fieldid_fielddefs_id`
    FOREIGN KEY (`fieldid`)
    REFERENCES `bugs`.`fielddefs` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_profiles_activity_userid_profiles_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_profiles_activity_who_profiles_userid`
    FOREIGN KEY (`who`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`quips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`quips` (
  `quipid` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `userid` MEDIUMINT(9) NULL DEFAULT NULL,
  `quip` VARCHAR(512) NOT NULL,
  `approved` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`quipid`),
  INDEX `fk_quips_userid_profiles_userid` (`userid` ASC),
  CONSTRAINT `fk_quips_userid_profiles_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`rep_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`rep_platform` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `visibility_value_id` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rep_platform_value_idx` (`value` ASC),
  INDEX `rep_platform_sortkey_idx` (`sortkey` ASC, `value` ASC),
  INDEX `rep_platform_visibility_value_id_idx` (`visibility_value_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`reports` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `user_id` MEDIUMINT(9) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `query` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reports_user_id_idx` (`user_id` ASC, `name` ASC),
  CONSTRAINT `fk_reports_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`resolution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`resolution` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  `visibility_value_id` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `resolution_value_idx` (`value` ASC),
  INDEX `resolution_sortkey_idx` (`sortkey` ASC, `value` ASC),
  INDEX `resolution_visibility_value_id_idx` (`visibility_value_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`series` (
  `series_id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `creator` MEDIUMINT(9) NULL DEFAULT NULL,
  `category` SMALLINT(6) NOT NULL,
  `subcategory` SMALLINT(6) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `frequency` SMALLINT(6) NOT NULL,
  `query` MEDIUMTEXT NOT NULL,
  `is_public` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`series_id`),
  UNIQUE INDEX `series_category_idx` (`category` ASC, `subcategory` ASC, `name` ASC),
  INDEX `series_creator_idx` (`creator` ASC),
  INDEX `fk_series_subcategory_series_categories_id` (`subcategory` ASC),
  CONSTRAINT `fk_series_category_series_categories_id`
    FOREIGN KEY (`category`)
    REFERENCES `bugs`.`series_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_series_creator_profiles_userid`
    FOREIGN KEY (`creator`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_series_subcategory_series_categories_id`
    FOREIGN KEY (`subcategory`)
    REFERENCES `bugs`.`series_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`series_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`series_data` (
  `series_id` MEDIUMINT(9) NOT NULL,
  `series_date` DATETIME NOT NULL,
  `series_value` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `series_data_series_id_idx` (`series_id` ASC, `series_date` ASC),
  CONSTRAINT `fk_series_data_series_id_series_series_id`
    FOREIGN KEY (`series_id`)
    REFERENCES `bugs`.`series` (`series_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`setting_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`setting_value` (
  `name` VARCHAR(32) NOT NULL,
  `value` VARCHAR(32) NOT NULL,
  `sortindex` SMALLINT(6) NOT NULL,
  UNIQUE INDEX `setting_value_nv_unique_idx` (`name` ASC, `value` ASC),
  UNIQUE INDEX `setting_value_ns_unique_idx` (`name` ASC, `sortindex` ASC),
  CONSTRAINT `fk_setting_value_name_setting_name`
    FOREIGN KEY (`name`)
    REFERENCES `bugs`.`setting` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`status_workflow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`status_workflow` (
  `old_status` SMALLINT(6) NULL DEFAULT NULL,
  `new_status` SMALLINT(6) NOT NULL,
  `require_comment` TINYINT(4) NOT NULL DEFAULT '0',
  UNIQUE INDEX `status_workflow_idx` (`old_status` ASC, `new_status` ASC),
  INDEX `fk_status_workflow_new_status_bug_status_id` (`new_status` ASC),
  CONSTRAINT `fk_status_workflow_new_status_bug_status_id`
    FOREIGN KEY (`new_status`)
    REFERENCES `bugs`.`bug_status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_status_workflow_old_status_bug_status_id`
    FOREIGN KEY (`old_status`)
    REFERENCES `bugs`.`bug_status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`tokens` (
  `userid` MEDIUMINT(9) NULL DEFAULT NULL,
  `issuedate` DATETIME NOT NULL,
  `token` VARCHAR(16) NOT NULL,
  `tokentype` VARCHAR(16) NOT NULL,
  `eventdata` TINYTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`token`),
  INDEX `tokens_userid_idx` (`userid` ASC),
  CONSTRAINT `fk_tokens_userid_profiles_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`ts_error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`ts_error` (
  `error_time` INT(11) NOT NULL,
  `jobid` INT(11) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `funcid` INT(11) NOT NULL DEFAULT '0',
  INDEX `ts_error_funcid_idx` (`funcid` ASC, `error_time` ASC),
  INDEX `ts_error_error_time_idx` (`error_time` ASC),
  INDEX `ts_error_jobid_idx` (`jobid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`ts_exitstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`ts_exitstatus` (
  `jobid` INT(11) NOT NULL AUTO_INCREMENT,
  `funcid` INT(11) NOT NULL DEFAULT '0',
  `status` SMALLINT(6) NULL DEFAULT NULL,
  `completion_time` INT(11) NULL DEFAULT NULL,
  `delete_after` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`jobid`),
  INDEX `ts_exitstatus_funcid_idx` (`funcid` ASC),
  INDEX `ts_exitstatus_delete_after_idx` (`delete_after` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`ts_funcmap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`ts_funcmap` (
  `funcid` INT(11) NOT NULL AUTO_INCREMENT,
  `funcname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`funcid`),
  UNIQUE INDEX `ts_funcmap_funcname_idx` (`funcname` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`ts_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`ts_job` (
  `jobid` INT(11) NOT NULL AUTO_INCREMENT,
  `funcid` INT(11) NOT NULL,
  `arg` LONGBLOB NULL DEFAULT NULL,
  `uniqkey` VARCHAR(255) NULL DEFAULT NULL,
  `insert_time` INT(11) NULL DEFAULT NULL,
  `run_after` INT(11) NOT NULL,
  `grabbed_until` INT(11) NOT NULL,
  `priority` SMALLINT(6) NULL DEFAULT NULL,
  `coalesce` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`jobid`),
  UNIQUE INDEX `ts_job_funcid_idx` (`funcid` ASC, `uniqkey` ASC),
  INDEX `ts_job_run_after_idx` (`run_after` ASC, `funcid` ASC),
  INDEX `ts_job_coalesce_idx` (`coalesce` ASC, `funcid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`ts_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`ts_note` (
  `jobid` INT(11) NOT NULL,
  `notekey` VARCHAR(255) NULL DEFAULT NULL,
  `value` LONGBLOB NULL DEFAULT NULL,
  UNIQUE INDEX `ts_note_jobid_idx` (`jobid` ASC, `notekey` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`user_api_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`user_api_keys` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` MEDIUMINT(9) NOT NULL,
  `api_key` VARCHAR(40) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `revoked` TINYINT(4) NOT NULL DEFAULT '0',
  `last_used` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_api_keys_api_key_idx` (`api_key` ASC),
  INDEX `user_api_keys_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_api_keys_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`user_group_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`user_group_map` (
  `user_id` MEDIUMINT(9) NOT NULL,
  `group_id` MEDIUMINT(9) NOT NULL,
  `isbless` TINYINT(4) NOT NULL DEFAULT '0',
  `grant_type` TINYINT(4) NOT NULL DEFAULT '0',
  UNIQUE INDEX `user_group_map_user_id_idx` (`user_id` ASC, `group_id` ASC, `grant_type` ASC, `isbless` ASC),
  INDEX `fk_user_group_map_group_id_groups_id` (`group_id` ASC),
  CONSTRAINT `fk_user_group_map_group_id_groups_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `bugs`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_group_map_user_id_profiles_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`versions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`versions` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(64) NOT NULL,
  `product_id` SMALLINT(6) NOT NULL,
  `isactive` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `versions_product_id_idx` (`product_id` ASC, `value` ASC),
  CONSTRAINT `fk_versions_product_id_products_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `bugs`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`watch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`watch` (
  `watcher` MEDIUMINT(9) NOT NULL,
  `watched` MEDIUMINT(9) NOT NULL,
  UNIQUE INDEX `watch_watcher_idx` (`watcher` ASC, `watched` ASC),
  INDEX `watch_watched_idx` (`watched` ASC),
  CONSTRAINT `fk_watch_watched_profiles_userid`
    FOREIGN KEY (`watched`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_watch_watcher_profiles_userid`
    FOREIGN KEY (`watcher`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`whine_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`whine_events` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `owner_userid` MEDIUMINT(9) NOT NULL,
  `subject` VARCHAR(128) NULL DEFAULT NULL,
  `body` MEDIUMTEXT NULL DEFAULT NULL,
  `mailifnobugs` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_whine_events_owner_userid_profiles_userid` (`owner_userid` ASC),
  CONSTRAINT `fk_whine_events_owner_userid_profiles_userid`
    FOREIGN KEY (`owner_userid`)
    REFERENCES `bugs`.`profiles` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`whine_queries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`whine_queries` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `eventid` MEDIUMINT(9) NOT NULL,
  `query_name` VARCHAR(64) NOT NULL DEFAULT '',
  `sortkey` SMALLINT(6) NOT NULL DEFAULT '0',
  `onemailperbug` TINYINT(4) NOT NULL DEFAULT '0',
  `title` VARCHAR(128) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `whine_queries_eventid_idx` (`eventid` ASC),
  CONSTRAINT `fk_whine_queries_eventid_whine_events_id`
    FOREIGN KEY (`eventid`)
    REFERENCES `bugs`.`whine_events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bugs`.`whine_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugs`.`whine_schedules` (
  `id` MEDIUMINT(9) NOT NULL AUTO_INCREMENT,
  `eventid` MEDIUMINT(9) NOT NULL,
  `run_day` VARCHAR(32) NULL DEFAULT NULL,
  `run_time` VARCHAR(32) NULL DEFAULT NULL,
  `run_next` DATETIME NULL DEFAULT NULL,
  `mailto` MEDIUMINT(9) NOT NULL,
  `mailto_type` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `whine_schedules_run_next_idx` (`run_next` ASC),
  INDEX `whine_schedules_eventid_idx` (`eventid` ASC),
  CONSTRAINT `fk_whine_schedules_eventid_whine_events_id`
    FOREIGN KEY (`eventid`)
    REFERENCES `bugs`.`whine_events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
